name: Test

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Prepare VM
        run: |
            apt update
            apt install -y libhdf4-dev
            apt install -y libgeos-dev
            apt install -y curl
            apt install ffmpeg libsm6 libxext6  -y
            apt install -y wget
            pip install torch~=1.13.1 torchvision~=0.14.1 --index-url https://download.pytorch.org/whl/cpu
            conda install -c conda-forge geos
            
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: PyTest
        run: |
            pytest tests
