name: Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
    REPOSITORY: '${{ github.repository }}'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set lower case
        run: |
          echo "IMAGE_NAME=ghcr.io/${REPOSITORY,,}" >>${GITHUB_ENV}
        
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        run: |
          docker build . -t ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:latest
          
