name: Test

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare VM
        run: |
            apt install -y libhdf4-dev
            apt install -y libgeos-dev
            apt install ffmpeg libsm6 libxext6  -y
            pip install torch~=1.13.1 torchvision~=0.14.1 --index-url https://download.pytorch.org/whl/cpu
            conda install -c conda-forge geos
            
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install git+https://github.com/NiroRNS/banet_v0.6_fix.git@v0.6


      - name: PyTest
        run: |
            pytest tests
