name: Test

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare VM
        run: |
            pip install torch~=1.13.1 torchvision~=0.14.1 --index-url https://download.pytorch.org/whl/cpu
            conda install -c conda-forge geos
            
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sed -i '/from nbdev.imports import test_eq/d' /opt/conda/lib/python3.10/site-packages/banet/core.py

      - name: PyTest
        run: |
            pytest tests
